### ISSUE TITLE
统一webp格式的可能方案

### ISSUE THREAD

**Issue by s-chance** [kuailemao/Ruyu-Blog#3]
可以使用 [imgproxy](https://github.com/imgproxy/imgproxy) 第三方图片处理项目，可以对 minio 中的图片进行 webp 格式转换。

不过这种方案，在 minio 中还是会存储原始的图片，只是通过 imgproxy 处理得到了对应的 webp 格式的url。

**Comment by s-chance** [comment]
> 可以使用 [imgproxy](https://github.com/imgproxy/imgproxy) 第三方图片处理项目，可以对 minio 中的图片进行 webp 格式转换。
> 
> 不过这种方案，在 minio 中还是会存储原始的图片，只是通过 imgproxy 处理得到了对应的 webp 格式的url。

一份可能的响应示例：

```json
{
    "msg": "上传成功",
    "data": {
        "origin": "http://127.0.0.1:9000/image/2024-09-02/ad6eb812ccbf4f80aced5a6025c64e21-20211009002649467.jpg",
        "webp": "http://127.0.0.1:8080/insecure/plain/s3://image/2024-09-02/ad6eb812ccbf4f80aced5a6025c64e21-20211009002649467.jpg@webp"
    }
}

**Comment by s-chance** [comment]
单张图片访问用时对比，原图 png 格式大小为 4 MB 左右，webp 格式大小为 421 KB 左右。

**Comment by kuailemao** [comment]
> 单张图片访问用时对比，原图 png 格式大小为 4 MB 左右，webp 格式大小为 421 KB 左右。
> 
> ## 访问 minio 的 png 格式图片用时
> ![图像](https://private-user-images.githubusercontent.com/91258620/363753378-fd47dacc-cac6-40d0-809d-4ba86c38b224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTY1NzgsIm5iZiI6MTcyNTI5NjI3OCwicGF0aCI6Ii85MTI1ODYyMC8zNjM3NTMzNzgtZmQ0N2RhY2MtY2FjNi00MGQwLTgwOWQtNGJhODZjMzhiMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE2NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTk2ZGUyZjkxYWQ3YzUxZWRjNTJhNDY2NDg2ZDMxYWY5NjcxYmM2OWQxMjhlMTUxMjBkYWEyMTAzMjY5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gsx-T5kO_XAbk2gygLTz2M-kzlMXHKyrGNers1tr6MA)
> 
> ## 访问 imgproxy 转换的 webp 格式图片用时
> ![图像](https://private-user-images.githubusercontent.com/91258620/363753770-c16494b6-0765-4f1d-ae25-ff8507460ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTY1NzgsIm5iZiI6MTcyNTI5NjI3OCwicGF0aCI6Ii85MTI1ODYyMC8zNjM3NTM3NzAtYzE2NDk0YjYtMDc2NS00ZjFkLWFlMjUtZmY4NTA3NDYwZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE2NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZWQxNWI4ZThiNzBkYmE0YzQ0YTU5ZWY4YTJhNzIxZjE4M2I1MjY2NDQ5ZTk2MTUwZjliN2UxNmYyNzllNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._OBTIsqlbDYOusUlbRJQDLa-FbQ0CwHMAVCesD22vy4)
> 
> ## 访问 minio 的 webp 格式图片用时
> ![image](https://private-user-images.githubusercontent.com/91258620/363754136-3f3402da-c747-452c-8002-439e290a4024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTY1NzgsIm5iZiI6MTcyNTI5NjI3OCwicGF0aCI6Ii85MTI1ODYyMC8zNjM3NTQxMzYtM2YzNDAyZGEtYzc0Ny00NTJjLTgwMDItNDM5ZTI5MGE0MDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE2NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGRjZTY1YWJkMzQyNWMxY2FhNWY0ZjM4NjIyNGNjNmUzNTk4MzgzMzI3MTUwYTQyYzZiOGUwMTI2OWIzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._g1YFhCkZmIErRMNb8x3MH93jNlN8f-VMDqV2yW6_Kg)

Java内置的imgproxy压缩大小吗？

**Comment by s-chance** [comment]
> Java内置的imgproxy压缩大小吗？

并不是 Java 原生具有的功能。

关于 Java 处理 webp 格式图片的库，如 (web-imageio)[https://mvnrepository.com/artifact/org.sejda.imageio/webp-imageio] 最后一次更新是四年前，可能缺乏对高版本 Jdk 的支持。

目前可能的方案就是使用类似 imgproxy 自建第三方图片转换服务，可以考虑将转换后的图片再存入 minio 或直接使用其转换 webp 格式的 url。

其他的方案就是考虑对 minio 进行增强，有一个类似的项目 (minio-plus)[https://minio-plus-docs.baldhead.cn/]。不过尚不明确该工具能否提供对 webp 格式自动转换的功能。

**Comment by s-chance** [comment]
可能是最简单的方案，前端使用 h5 的新特性 canvas 压缩图片格式为 webp 后上传

示例
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Image to WebP Converter</title>
  </head>
  <body>
    <input type="file" id="imageInput" accept="image/*" />
    <button onclick="convertToWebP()">Convert to WebP</button>

    <!-- 显示原始图像 -->
    <div>
      <h4>Original Image:</h4>
      <img id="originalImage" />
    </div>

    <!-- 显示转换后的 WebP 图像 -->
    <div>
      <h4>Converted WebP Image:</h4>
      <img id="webpImage" />
    </div>

    <script>
      let originalBlobUrl;

      document
        .getElementById("imageInput")
        .addEventListener("change", function (event) {
          const file = event.target.files[0];
          if (file) {
            originalBlobUrl = URL.createObjectURL(file);
            document.getElementById("originalImage").src = originalBlobUrl;
          }
        });

      function convertToWebP() {
        const input = document.getElementById("imageInput");
        const file = input.files[0];
        if (file) {
          const reader = new FileReader();
          reader.onload = function (e) {
            const img = new Image();
            img.onload = function () {
              const canvas = document.createElement("canvas");
              const ctx = canvas.getContext("2d");
              canvas.width = img.width;
              canvas.height = img.height;
              ctx.drawImage(img, 0, 0);
              canvas.toBlob(function (blob) {
                // 本地直接预览转换后的图片
                const webPUrl = URL.createObjectURL(blob);
                document.getElementById("webpImage").src = webPUrl;

                const formData = new FormData();
                const name = file.name.substring(0, file.name.lastIndexOf("."));
                formData.append("file", blob, name + ".webp");

                fetch("http://127.0.0.1:8081/upload/image", {
                  method: "POST",
                  body: formData,
                })
                  .then((respose) => respose.json())
                  .then((data) => {
                    console.log(data);
                    // document.getElementById("webpImage").src = data.data.origin;
                  })
                  .catch((error) => console.log(error));
              }, "image/webp");
            };
            img.src = e.target.result;
          };
          reader.readAsDataURL(file);
        }
      }
    </script>
  </body>
</html>
```

上传图片调用 `convertToWebP` 方法，通过 canvas api 转换图片格式为 webp 后再上传至后端。转换是在前端完成，对于后端来说只需要接收转换完成的webp格式图片文件。压缩质量可进行简单调整。

相关方法参考文档 [HTMLCanvasElement.toBlob()](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLCanvasElement/toBlob)

**Comment by s-chance** [comment]
补充：可能是最简单的方案，前端使用 h5 的新特性 canvas 压缩图片格式为 webp 后上传，如果已经实现可忽略这条 comment。

示例
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Image to WebP Converter</title>
  </head>
  <body>
    <input type="file" id="imageInput" accept="image/*" />
    <button onclick="convertToWebP()">Convert to WebP</button>

    <!-- 显示原始图像 -->
    <div>
      <h4>Original Image:</h4>
      <img id="originalImage" />
    </div>

    <!-- 显示转换后的 WebP 图像 -->
    <div>
      <h4>Converted WebP Image:</h4>
      <img id="webpImage" />
    </div>

    <script>
      let originalBlobUrl;

      document
        .getElementById("imageInput")
        .addEventListener("change", function (event) {
          const file = event.target.files[0];
          if (file) {
            originalBlobUrl = URL.createObjectURL(file);
            document.getElementById("originalImage").src = originalBlobUrl;
          }
        });

      function convertToWebP() {
        const input = document.getElementById("imageInput");
        const file = input.files[0];
        if (file) {
          const reader = new FileReader();
          reader.onload = function (e) {
            const img = new Image();
            img.onload = function () {
              const canvas = document.createElement("canvas");
              const ctx = canvas.getContext("2d");
              canvas.width = img.width;
              canvas.height = img.height;
              ctx.drawImage(img, 0, 0);
              canvas.toBlob(function (blob) {
                // 本地直接预览转换后的图片
                const webPUrl = URL.createObjectURL(blob);
                document.getElementById("webpImage").src = webPUrl;

                const formData = new FormData();
                const name = file.name.substring(0, file.name.lastIndexOf("."));
                formData.append("file", blob, name + ".webp");

                fetch("http://127.0.0.1:8081/upload/image", {
                  method: "POST",
                  body: formData,
                })
                  .then((respose) => respose.json())
                  .then((data) => {
                    console.log(data);
                    // document.getElementById("webpImage").src = data.data.origin;
                  })
                  .catch((error) => console.log(error));
              }, "image/webp");
            };
            img.src = e.target.result;
          };
          reader.readAsDataURL(file);
        }
      }
    </script>
  </body>
</html>
```

上传图片调用 `convertToWebP` 方法，通过 canvas api 转换图片格式为 webp 后再上传至后端。转换是在前端完成，对于后端来说只需要接收转换完成的webp格式图片文件。压缩质量可进行简单调整。

相关方法参考文档 [HTMLCanvasElement.toBlob()](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLCanvasElement/toBlob)
